### ISSUE TITLE
文叔叔上传失败

### ISSUE THREAD

**Issue by fbigun** [Mikubill/transfer#15]
```bash
root@localhost:~# ./transfer wss transfer
Local: /root/transfer
getSendConfig(single mode) returns error: post https://www.wenshushu.cn/ap/task/addsend returns error: unexpected end of JSON input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78c4c8]

goroutine 1 [running]:
transfer/apis/public/wenshushu.(*wssTransfer).initUpload(0xc00011c9c0, 0x7ca000, 0x1)
        /github/workspace/apis/public/wenshushu/upload.go:45 +0x138
transfer/apis/public/wenshushu.(*wssTransfer).PreUpload(0xc00011c9c0, 0x7ffc0ce2c63e, 0x8, 0x7ca000, 0x0, 0x0)
        /github/workspace/apis/public/wenshushu/upload.go:50 +0x59
transfer/apis.upload(0x7ffc0ce2c63e, 0x8, 0x7ca000, 0x912b60, 0xc00011c9c0, 0x1, 0x1, 0x16, 0x0)
        /github/workspace/apis/upload.go:94 +0x198
transfer/apis.Upload(0xc00010b4c0, 0x1, 0x1, 0x912b60, 0xc00011c9c0)
        /github/workspace/apis/upload.go:67 +0x332
transfer/cmd.runner.func1(0xc00012ab00, 0xc00010b4b0, 0x1, 0x1)
        /github/workspace/cmd/controller.go:64 +0x90
github.com/spf13/cobra.(*Command).execute(0xc00012ab00, 0xc00010b470, 0x1, 0x1, 0xc00012ab00, 0xc00010b470)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xbc5900, 0x1, 0x1, 0xbc60e0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
transfer/cmd.Execute()
        /github/workspace/cmd/root.go:83 +0x53
main.main()
        /github/workspace/main.go:6 +0x20
```

**Comment by Mikubill** [comment]
该问题已修复，请使用新版程序上传。
