### ISSUE TITLE
多个云盘可上传但无法下载

### ISSUE THREAD

**Issue by genius210** [Mikubill/transfer#65]
测试了wss和muse都无法通过transfer下载，网页是可以下载的。其他的网盘还没有测试。
wss下载时报错：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x749029]

goroutine 1 [running]:
github.com/Mikubill/transfer/apis/public/quickfile.(*quick).LinkMatcher(0x0?, {0x7ffed8f54e3b?, 0x2b?})
        <autogenerated>:1 +0x29
github.com/Mikubill/transfer/cmd.ParseLink({0x7ffed8f54e3b, 0x2b})
        /home/runner/work/transfer/transfer/cmd/controller.go:58 +0xc4
github.com/Mikubill/transfer/cmd.runner.func1(0x8c4010?, {0xc00013a010?, 0x1, 0x1})
        /home/runner/work/transfer/transfer/cmd/controller.go:88 +0x15d
github.com/Mikubill/transfer/cmd.handleRootTransfer({0xc00013a010, 0x1, 0x1})
        /home/runner/work/transfer/transfer/cmd/root.go:103 +0x143
github.com/Mikubill/transfer/cmd.Execute()
        /home/runner/work/transfer/transfer/cmd/root.go:85 +0xca
main.main()
        /home/runner/work/transfer/transfer/main.go:6 +0x17

muse下载提示403 Forbidden：
fetching ticket..ok
fetching download metadata..ok
download failed on https://musetransfer.com/s/5ajskjih4, returns link unavailable, 403 Forbidden

**Comment by Mikubill** [comment]
确认。近期统一修复

**Comment by 1-1-2** [comment]
go-file (gof) 也有无法下载的情况

```
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/Mikubill/transfer/apis/public/gofile.goFile.download({{{0x0, 0x0}, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /home/runner/work/transfer/transfer/apis/public/gofile/download.go:32 +0x53a
github.com/Mikubill/transfer/apis/public/gofile.goFile.DoDownload({{{0x0, 0x0}, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /home/runner/work/transfer/transfer/apis/public/gofile/download.go:23 +0x7f
github.com/Mikubill/transfer/apis.Download({0x7fff965397b5, 0x1a}, {0x7f45b4746360, 0xc0000fc200})
        /home/runner/work/transfer/transfer/apis/download.go:18 +0x14d
github.com/Mikubill/transfer/cmd.runner.func1(0x8c4010?, {0xc00008a010?, 0x1, 0x1})
        /home/runner/work/transfer/transfer/cmd/controller.go:90 +0x17d
github.com/Mikubill/transfer/cmd.handleRootTransfer({0xc00008a010, 0x1, 0x1})
        /home/runner/work/transfer/transfer/cmd/root.go:103 +0x143
github.com/Mikubill/transfer/cmd.Execute()
        /home/runner/work/transfer/transfer/cmd/root.go:85 +0xca
main.main()
        /home/runner/work/transfer/transfer/main.go:6 +0x17
```
